Cats99/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "cats#index" #TBT ON INTRUSTOR
  resources :cats, only: [:index, :show, :create, :update, :new, :edit]

end

Cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Cats99/app/models/cat.rb
class Cat < ApplicationRecord
  VALID_COLORS = %w(orange brown white black)
  validates :birth_date, :color, :name, :sex, presence: true
  validates :sex, inclusion: { in: %w(M F), message: "%{value} is not a valid sex" }
  validates :color, inclusion: { in: VALID_COLORS, message: "%{value} is not a valid color"}
  validate :birth_date_cannot_be_the_future



  def birth_date_cannot_be_the_future
    if birth_date > Date.today
      errors.add(:birth_date, "can't be in the future")
    end
  end
end

Cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render json: @cat
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save!
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_url cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def new
    @cat = Cat.new
    render :new
  end
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

Cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats99/app/helpers/cats_helper.rb
module CatsHelper
end

Cats99/app/views/cats/_cat.html.erb
<ul>
    <li>
        <%= cat.name %>
    </li>
    <li>
        <%= cat.birth_date %>
    </li>
        <li>
        <%= cat.color %>
    </li>
        <li>
        <%= cat.sex %>
    </li>
        <li>
        <%= cat.description %>
    </li>
</ul>

Cats99/app/views/cats/edit.html.erb
<form action="<%= cats_url(@cat) %>">

</form>

Cats99/app/views/cats/index.html.erb
<h1> CATS </h1>
    <ul>
    <% @cats.each do  |cat| %>
        <li>
            <%= render 'cat', cat: cat, type: :index %>
        </li>
    <% end %>
    </ul>

Cats99/app/views/cats/new.html.erb
<form action="<%= cats_url %>" value="POST">
<label for="name">Name:
<input type="text" id="name" name="cat[name]" value="@cat.name">
</label>
<label for="sex">Sex:
<input type="radio" id="M" name="cat[sex]" value="@cat.sex">
  <label for="M">Male</label>
  <input type="radio" id="F" name="cat[sex]" valeu="@cat.sex">
  <label for="F">Female</label>
</label>
<label for="color">Color:
<input type="text" id="color" name="cat[color]" value="@cat.color">
</label>
<label for="birth_date">Birth Date
<input type="date" id="birth_date" name="cat[birth_date]" value="@cat.birth_date">
</label>
<label for="description">Description
<input type="text" id="description" name="cat[description]" value="@cat.description">
</label>
</form>

Cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>